PhoenicisOrg/scripts

Functions/Apps/Resources/script.js, Functions/Shortcuts/Wine/script.js
renamed bean appsManager to appsSource (appsManager does not exist anymore)
=> fixed appsSource beans

Functions/QuickScript/SteamScript/script.js
=> added SteamScript to install steam applications

Games/Black Mesa/Steam/script.js, Games/Hexcells Infinite/Steam/script.js, Games/Hexcells Plus/Steam/script.js, Games/Hexcells/Steam/script.js, Games/The Elder Scrolls V: Skyrim/Steam/script.js
default category "Games" is set in SteamScript
=> steam games: use default category

Functions/QuickScript/SteamScript/script.js
does not work with Steam protocoll
=> fixed Steam "-silent"

Functions/QuickScript/InstallerScript/script.js, Functions/QuickScript/SteamScript/script.js, Functions/QuickScript/ZipScript/script.js, Games/Assassin’s Creed: Brotherhood/Steam/script.js
=> Pass wizard in pre/postInstall function

Functions/Engines/Wine/script.js, Functions/QuickScript/SteamScript/script.js
- disabled silent download while progress bar does not work
- added hint to close Steam after Steam setup
=> Enhanced SteamScript

Functions/Engines/Wine/script.js
Fixes: Implement wine.soundDriver() #35
=> allow to change sound driver

Functions/Engines/Wine/script.js
=> Allow to set OS per application

Functions/QuickScript/SteamScript/script.js
fixes: SteamScript: manual app homepage and executable overwritten #77
=> SteamScript: do not overwrite with defaults

Functions/Engines/Wine/script.js
fixes: Implement wine.setManaged() #26
=> implemented wine.managed()

Functions/Engines/Wine/script.js, Functions/QuickScript/QuickScript/script.js
=> use 32bit wine by default

Development/Notepad++/v7.2.2/script.js, Functions/QuickScript/InstallerScript/script.js, Functions/QuickScript/LocalInstallerScript/script.js, Functions/QuickScript/OnlineInstallerScript/script.js, Functions/QuickScript/RemoteInstallerScript/script.js, Games/Steam/Online/script.js, Graphics/Photofiltre/Online/script.js, Internet/mIRC/v7.46/script.js
fixes: Enhance InstallerScript for local files #88
=> implemented Local/RemoteInstallerScript

Functions/Engines/Wine/script.js, Functions/Net/Resource/script.js
fixes: [PoL issue #396](https://github.com/PlayOnLinux/POL-POM-5/issues/396)
=> install gecko and mono

Functions/Engines/Wine/script.js
fixes: Implement wine.useNativeExtension() #39
=> use native application for certain file extension

Functions/Verbs/corefonts/script.js
fixes: Corefonts seems to be broken #104
=> fixed corefonts

Functions/Engines/Wine/script.js
Use default value only if nothing else set.
fixes: PlayOnLinux/POL-POM-5#463
=> fixed wine architecture

Functions/Verbs/d3dx9/script.js
fixes https://github.com/PlayOnLinux/POL-POM-5/issues/465
=> Fix filesnames for 32bit d3dx9

Functions/Verbs/quicktime76/script.js
fixes: implement quicktime76 #118
=> quicktime76

Functions/Engines/Wine/script.js
=> fix wineArchitecture regression (Fixes #120)

Functions/Verbs/tahoma/script.js
There was a problem with checksum verification, so I updated them.
=> Fix tahoma Verb (DL links and checksums)

Functions/Verbs/quicktime76/script.js
fixes #118  
Thanks @plata for implementation
=> Make quicktime not silent to fix it (Fixes #118)

Custom/OnlineInstaller/Online/script.js, Functions/QuickScript/InstallerScript/script.js, Functions/QuickScript/QuickScript/script.js
Would be great to have a bean to list the available options in a combobox.
=> custom installer: let user select wine settings

Functions/QuickScript/InstallerScript/script.js
The installation crashed when not using custom wine settings.
=> fixed installer script

Functions/Shortcuts/Wine/script.js
com.phoenicis -> org.phoenicis
fixes #160
=> fixed ShortcutDTO Builder path

Custom/LocalInstaller/Local/script.js, Custom/OnlineInstaller/Online/script.js, Functions/Engines/Wine/script.js, Functions/QuickScript/InstallerScript/script.js, Functions/QuickScript/QuickScript/script.js
fixes PlayOnLinux/POL-POM-5#540
=> allow to set Windows version in custom installer

Custom/LocalInstaller/Local/script.js, Custom/OnlineInstaller/Online/script.js, Functions/QuickScript/InstallerScript/script.js, Internet/Internet Explorer 7.0/Online/script.js
fixes: PlayOnLinux/POL-POM-5#581
requires: PlayOnLinux/POL-POM-5#592
=> update for: wizard menu returns index; custom installer: show recommended

Functions/QuickScript/CustomInstallerScript/script.js, Functions/QuickScript/InstallerScript/script.js, Functions/QuickScript/LocalInstallerScript/script.js, Functions/QuickScript/OnlineInstallerScript/script.js
CustomInstallerScript allows to specify a function which returns the installer script path.
=> added installation args for InstallerScript and CustomInstallerScript

Games/League of Legends/BETA Client/script.js, Games/League of Legends/application.json
This script should work.
It creates a shortcut for the launcher and one for the LeagueClient.exe.
=> update LoL Beta script

Functions/Engines/Wine/script.js
Allows wine to execute bat and msi files
=> Allows wine to execute bat and msi files

Functions/Engines/Wine/script.js
added the winepath method to Wine, which converts Unix paths to winepaths
split from #184
=> add winepath

Functions/Apps/Resources/script.js, Functions/Shortcuts/Wine/script.js
fixes PlayOnLinux/POL-POM-5#669
=> renamed appsSource to repository

Functions/Apps/Resources/script.js, Functions/Shortcuts/Wine/script.js
This PR solves issue https://github.com/PlayOnLinux/POL-POM-5/issues/695.
=> Fix missing bean "repository" error

Internet/Internet Explorer 7.0/Online/script.js
=> fixed IE7 language selection

Internet/Internet Explorer 6.0/Online/script.js
=> IE6: use win2k

Functions/Engines/Wine/script.js
setVirtualDesktop = function (width, height)
Requires two variables - width and height of window.
Script creates a new enties in Windows Registry to create new Virtual Desktop with name "Default" and set up resolution with width and height variables.
=> Add new function - setVirtualDesktop

Functions/QuickScript/UplayScript/script.js
You can determine the app ID by starting the download and checking the folders in `Ubisoft/Ubisoft Game Launcher/data/`.
I could not yet figure out if it is possible to close Uplay automatically.
=> QuickScript for Uplay

Functions/Engines/Wine/script.js
fixes PlayOnLinux/POL-POM-5#687
fixes PlayOnLinux/POL-POM-5#511
=> disable winemenubuilder

Functions/QuickScript/InstallerScript/script.js, Functions/QuickScript/LocalInstallerScript/script.js, Functions/QuickScript/OnlineInstallerScript/script.js
=> InstallerScript: enable install arguments

Functions/Shortcuts/Wine/script.js
Needs PlayOnLinux/POL-POM-5#854 to be merged.
=> Change WineShortcut to make use of the new method getMainMiniature() in ApplicationDTO

Functions/QuickScript/InstallerScript/script.js, Functions/QuickScript/LocalInstallerScript/script.js, Functions/QuickScript/OnlineInstallerScript/script.js
Reverts PlayOnLinux/Scripts#244
fixes PlayOnLinux/POL-POM-5#866
=> Revert "InstallerScript: enable install arguments"

Games/League of Legends/BETA Client/script.js
=> - Remove "/q" from the League of Legends installation args

Functions/QuickScript/LocalInstallerScript/script.js, Functions/QuickScript/OnlineInstallerScript/script.js
Had to revert #244 because of PlayOnLinux/POL-POM-5#866.
required by #231
=> Local/OnlineInstallerScript: enable install arguments

Functions/Engines/Wine/script.js, Functions/Filesystem/Files/script.js, Functions/Net/Resource/script.js, Functions/QuickScript/InstallerScript/script.js, Functions/QuickScript/SteamScript/script.js, Functions/QuickScript/UplayScript/script.js, Functions/QuickScript/ZipScript/script.js, Functions/Verbs/corefonts/script.js, Functions/Verbs/d3dx9/script.js, Internet/Internet Explorer 6.0/Online/script.js, Internet/Internet Explorer 7.0/Online/script.js, i18n/Messages_de.properties, i18n/de.po, i18n/keys.pot
=> streamlined messages

Functions/Verbs/d3dx10/script.js
This PR fixes #276.
I used https://github.com/Winetricks/winetricks/blob/master/src/winetricks and https://github.com/PlayOnLinux/Scripts/blob/master/Functions/Verbs/d3dx9/script.js as a guideline.
=> Add DirectX 10

Internet/category.json
Fixes https://github.com/PlayOnLinux/POL-POM-5/issues/957 and 'No Games are visible in Apps #298'
=> Fix Internet Category Name

Games/STAR WARS Jedi Knight - Jedi Academy/Steam/script.json, Games/STAR WARS Jedi Knight - Mysteries of the Sith/Steam/script.json, Games/STAR WARS Jedi Knight II - Jedi Outcast/Steam/script.json, Games/STAR WARS Jedi Knight: Dark Forces II/Steam/script.json
testing must be a subset of compatible
=> STAR WARS Jedi Knight: fixed compatibleOperatingSystems

Wine/Engine/Object/script.js
see: <https://www.winehq.org/announce/2.0.2>
=> updated Wine stable version to 2.0.2

Engines/Wine/Engine/Object/script.js
See [this bug](https://github.com/PlayOnLinux/POL-POM-5/issues/968) for more info
This is working flawlessly for me at the moment (tested with Europa Universalis 2)
=> Set correctly LD_LIBRARY_PATH

Engines/Wine/Verbs/uplay/script.js
Uplay doesn't start anymore if upc.exe uses Windows XP.
=> updated Uplay verb

Applications/Games/Uplay/Online/script.js
Uplay doesn't start anymore with the previous configuration.
=> updated Uplay

Engines/Wine/Engine/Object/script.js, Engines/Wine/Shortcuts/Reader/script.js, Engines/Wine/Shortcuts/Wine/script.js
fixes PhoenicisOrg/POL-POM-5#984
=> set wineprefix path from js

Applications/Games/STAR WARS - Empire at War - Gold Pack/application.json
=> Udpated Star Wars Empire At War

Applications/Games/League of Legends/BETA Client/script.json
Because the league of legends script is quite old and doesn't fully work we should change the script to testing to inform the users of the current state of the script.
Closes #179
=> Updated League of Legends: set to testing

Applications/Games/Unholy Heights/Steam/script.js
=> Updated Unholy Heights: Set wine version to 2.14 staging

Applications/Games/Warlock - Master of the Arcane/Steam/script.js
=> Updated Warlock - Master of the Arcane: set wine version to 2.14

Engines/Wine/Shortcuts/Reader/script.js
fixes PhoenicisOrg/POL-POM-5#448
=> updated Wine shortcut runner (do not wait until process finished)

Engines/Wine/Engine/Object/script.js
see PhoenicisOrg/POL-POM-5#1062
=> better naming for engine installations

Engines/Wine/QuickScript/InstallerScript/script.js, Engines/Wine/QuickScript/SteamScript/script.js, Engines/Wine/QuickScript/UplayScript/script.js, Engines/Wine/QuickScript/ZipScript/script.js
fixes PhoenicisOrg/POL-POM-5#1086
=> avoid setup wizard crash if application miniature cannot be found

Applications/Games/Tomb Raider Legend/Steam/script.js
crashes when starting from Steam
=> updated Tomb Raider: Legend (start trl.exe directly)

Engines/Wine/Engine/Object/script.js
=> prevent running 64bit binary in 32bit Wine prefix

Applications/Games/Tomb Raider Anniversary/Steam/script.js
If tra.exe is started directly, it complains that Steam cannot be found.
=> updated Tomb Raider: Anniversary (start via Steam)

Applications/Games/Assassin's Creed II/Steam/script.js, Applications/Games/Assassin's Creed III/Steam/script.js, Applications/Games/Assassin's Creed IV Black Flag/Steam/script.js, Applications/Games/Assassin's Creed Revelations/Steam/script.js, Applications/Games/Assassin's Creed Unity/Steam/script.js, Applications/Games/Assassin's Creed/Steam/script.js, Applications/Games/Assassin's Creed: Brotherhood/Steam/script.js, Applications/Games/Beyond Good and Evil/Uplay/script.js, Applications/Games/Far Cry 3 - Blood Dragon/Uplay/script.js, Applications/Games/Prince of Persia: The Sands of Time/Uplay/script.js, Applications/Games/Rayman Legends/Steam (Demo)/script.js, Applications/Games/Rayman Legends/Steam/script.js, Applications/Games/Rayman Origins/Uplay/script.js, Applications/Games/The Crew/Steam (Demo)/script.js, Applications/Games/The Crew/Steam/script.js, Applications/Games/Tom Clancy's Splinter Cell/Uplay/script.js, Applications/Games/Uplay/Local/script.js, Applications/Games/Uplay/Online/script.js
Wine staging 2.16 fixes missing text (libcef issue)
=> updated Uplay (games) with Wine staging 2.16

Engines/Wine/Verbs/dotnet40/script.js
see https://github.com/Winetricks/winetricks/commit/ddf5c7c059ebc9b78031584cb82332e091c52d28
=> updated Wine dotnet40 verb (allow for 64bit)

i18n/Messages_de.properties, i18n/Messages_fr.properties, i18n/de.po, i18n/fr.po, i18n/keys.pot, i18n/update_translations.py
Reduces the number of diffs when the translations are updated. The line numbers are useless anyways as they do not refer to the original file.
=> do not add line numbers in translation files

Engines/Wine/QuickScript/ZipScript/script.js
usage: do not specify url and checksum
=> updated ZipScript to install also local .zip files

Applications/Games/Earth Eternal - Valkal's Shadow/Online/script.json
As suggested, have correct to 'free'.
=> updated Earth Eternal - Valkal's Shadow

Engines/Wine/QuickScript/InstallerScript/script.js, Engines/Wine/QuickScript/QuickScript/script.js, Engines/Wine/QuickScript/SteamScript/script.js, Engines/Wine/QuickScript/UplayScript/script.js, Engines/Wine/QuickScript/ZipScript/script.js
requires PhoenicisOrg/POL-POM-5#1131
fixes #269
=> updated QuickScripts to get miniature from context

Applications/Games/Steam/Online/script.js, Engines/Wine/QuickScript/SteamScript/script.js
Without "-no-cef-sandbox" the shop doesn't load.
=> updated Steam: fixed shop

.eslintrc.yml
=> ESLint: check indentation

.travis.yml
=> Travis: install gettext

.travis.yml, i18n/update_translations.py
`xgettext` on Travis doesn't accept `file` parameter for `--add-location`.
=> fixed translation updates in Travis

.eslintrc.yml
=> ESLint: extend recommended ruleset + Nashorn env

README.md
use a more common style (see e.g. https://github.com/agis/git-style-guide#messages)
=> Update PR naming conventions

Applications/Games/League of Legends/BETA Client/script.js, Applications/Games/Q.U.B.E: Director's Cut/Steam/script.js, Applications/Office/Adobe Acrobat Reader DC/Online/script.js
see #527
Either I overlooked some or Codacy didn't show them.
=> Codacy: fix 'wizard' is defined but never used (cont'd)

Applications/Games/Wildlife Park 2/Local/script.js, Applications/Games/Wildlife Park 2/Steam/script.js
=> Update Wildlife Park 2 (fix preInstall)

Applications/Games/League of Legends/Client/script.js, Applications/Games/League of Legends/Client/script.json, Applications/Games/League of Legends/application.json
- Rename "League of Legends BETA Client" to "League Of Legends" (It isn't in beta anymore)
- Update installers checksums and installation method (That should fix
any issues with the launcher)
Everything should be working (on the launche and in-game)
This fix #464
=> Update League of Legends to make it work wit the new installer

Engines/Wine/Verbs/PhysX/script.js, Engines/Wine/Verbs/QuickTime 7.6/script.js, Engines/Wine/Verbs/Tahoma/script.js, Engines/Wine/Verbs/Uplay/script.js, Engines/Wine/Verbs/Windows XP SP 3/script.js, Engines/Wine/Verbs/corefonts/script.js, Engines/Wine/Verbs/crypt32/script.js, Engines/Wine/Verbs/d3dx10/script.js, Engines/Wine/Verbs/d3dx9/script.js, Engines/Wine/Verbs/dotnet40/script.js, Engines/Wine/Verbs/dotnet45/script.js, Engines/Wine/Verbs/dotnet452/script.js, Engines/Wine/Verbs/luna/script.js, Engines/Wine/Verbs/mfc42/script.js, Engines/Wine/Verbs/msls31/script.js, Engines/Wine/Verbs/mspatcha/script.js, Engines/Wine/Verbs/quartz/script.js, Engines/Wine/Verbs/sandbox/script.js, Engines/Wine/Verbs/secur32/script.js, Engines/Wine/Verbs/vcrun2003/script.js, Engines/Wine/Verbs/vcrun2005/script.js, Engines/Wine/Verbs/vcrun2008/script.js, Engines/Wine/Verbs/vcrun2010/script.js, Engines/Wine/Verbs/vcrun2012/script.js, Engines/Wine/Verbs/vcrun2013/script.js, Engines/Wine/Verbs/vcrun2015/script.js, Engines/Wine/Verbs/xact/script.js
=> Document Verbs

Applications/Office/ElsterFormular/Online/script.js
fixes ElsterFormular version 19
requires #596
=> Update ElsterFormular (use vcrun2017)

i18n/Messages.properties, i18n/update_translations.py
Crowdin needs key=value format.
fixes #591 (I hope)
=> Fix Messages.properties for Crowdin

Engines/Wine/Engine/Implementation/script.js, Engines/Wine/Engine/Object/script.js, Engines/Wine/Tools/Wine Terminal Opener/script.js
=> Fix Wine#binPath()

Engines/Wine/Plugins/regedit/script.js
=> Add delete functions for regedit

Engines/Wine/QuickScript/Steam Script/script.js
=> Fix SteamScript

Utils/Functions/Filesystem/Files/script.js
requires PhoenicisOrg/phoenicis#1336
=> Implement ls

Engines/Wine/QuickScript/Steam Script/script.js
=> Update SteamScript to fix .preInstall crashes

Engines/Wine/Engine/Object/script.js
=> Update Wine LATEST_STABLE_VERSION to 3.0.1

Applications/Internet/Internet Explorer 6.0/Online/script.js, Engines/Wine/Engine/Object/script.js
=> Update Internet Explorer 6.0

Engines/Wine/Engine/Object/script.js
cannot merge this right away (version is not yet available in Phoenicis)
=> Update Wine LATEST_DEVELOPMENT_VERSION to 3.12

Applications/Games/STAR WARS - Empire at War - Gold Pack/Local/script.js, Applications/Games/STAR WARS Battlefront II/Local/script.js, Applications/Internet/Internet Explorer 6.0/Online/script.js, Engines/Wine/Engine/Object/script.js, Engines/Wine/QuickScript/Steam Script/script.js, Engines/Wine/QuickScript/Uplay Script/script.js
fixes: SteamScript does not show download message
required to fix: SteamScript does not detect that download finished
=> Wine#runInsidePrefix(): add wait parameter

README.md, docs/_docs/Develop/script-js.md
=> Fix documentation (OOP API)

Engines/Wine/Plugins/Windows version/script.js
Setting the service pack didn't work.
=> Fix Wine Windows version plugin

.eslintrc.yml
=> Fix ESLint camelcase rule

.eslintrc.yml
Adding chmod to the list to fix Codacy errors.
=> Update .eslintrc.yml (add chmod to globals)

Engines/Wine/Engine/Implementation/script.js
=> Fix font antialasing issue on OSX 

.gitignore, Engines/Wine/Plugins/hdpi/script.js, Engines/Wine/Plugins/hdpi/script.json, Engines/Wine/Settings/hdpi/script.js, Engines/Wine/Settings/hdpi/script.json
=> [Mac] Wine engine: Add of HDPI (Retina) support

Applications/Games/Blizzard app/Online/script.js
=> Update Blizzard app, using Wine 3.19-staging and using deafult Windows version

docs/_docs/Develop/script-js.md
Fixes : https://github.com/PhoenicisOrg/scripts/issues/805#issuecomment-453751721
Signed-off-by: Jacob Hrbek <werifgx@gmail.com>
=> Documentation : Fixed typo

README.md
=> Add Crowdin link to README

Engines/Wine/Verbs/adobeair/script.js
=> Update AdobeAir, fixed crash upon installation window pops up

Applications/Games/Hearthstone/Online/script.js, Applications/Games/Hearthstone/Online/script.json
Bug : #792
Changes executable to workaround #792
Tested, working
Fixes : https://github.com/PhoenicisOrg/scripts/pull/793
Signed-off-by: Jacob Hrbek <werifgx@gmail.com>
=> Update Hearthstone to fix shortcut creation error

Engines/Wine/Engine/Object/script.js
Sorry for the commit, I did not see I was committing directly.
=> Update Wine.uninstall: return a boolean

Applications/Games/DC Universe Online/Online/script.json
Game was run for 4 hours straight and with that I assume the crashes I was getting last time are solved.
=> Update DC Universe Online, removed Linux from testing operating systems

Engines/Wine/Shortcuts/Wine/script.js
=> Fix shortcut creation

Engines/Wine/Verbs/FAudio/script.js
=> Update FAudio, changed version number to 19.03

Engines/Wine/Engine/Implementation/script.js
Before: "Please wait while wine?os=linux is downloaded..."
=> Improve message while downloading available Wine versions

Engines/Wine/Verbs/Tahoma/script.js
The previous links went down so I've looked at the link winetricks uses and pasted it into our verb.
=> Update Tahoma, changed link to a working one

Engines/Wine/Verbs/FAudio/script.js
=> Update FAudio, added version 19.05

Applications/Games/The Sims/Local/script.js
=> Update The Sims, using latest staging version

Engines/Wine/Settings/UseTakeFocus/script.js, Engines/Wine/Settings/UseTakeFocus/script.json
Add UseTakeFocus, Fixes #936, required for #937 GG
=> Add UseTakeFocus, Fixes #936, required for #937

Engines/Wine/Engine/Object/script.js
Others have not been build yet @qparis
=> Revert latest wine version to 4.0 and 4.7

docs/_docs/Develop/script-js.md
Fixes https://github.com/PhoenicisOrg/scripts/issues/989#issuecomment-499593708
=> Fix UplayScript documentation

Engines/Wine/Verbs/DXVK/script.js, Engines/Wine/Verbs/FAudio/script.js, Engines/Wine/Verbs/VK9/script.js
It will never work as expected without that ^^.
=> Update DXVK/Faudio/VK9: pass string instead of MenuItem

Applications/Games/The Sims 3/Local/script.js
Previous used version is now crashing the Sims3LauncherW.exe making it impossible to play. Tried other versions and settled down on this one.
=> Update The Sims 3 (use Wine stable)

Engines/Wine/Engine/Implementation/script.js
Fix #1005. 
Side note: the script (7-zip) stop after installing the runtime without any error.
=> Download latest runtime

Utils/Functions/Net/Download/script.js
This PR refactors the `Downloader` class with the newer `class` syntax
=> Refactor the Downloader class

Utils/Functions/Net/Resource/script.js
This PR refactors the Resource class with the new ES 6 `class` syntax
=> Refactor the Resource Class

Engines/Wine/QuickScript/Quick Script/script.js, Engines/Wine/Shortcuts/Wine/script.js
This PR refactors the `WineShortcut` class with the "new" class syntax and some other newer language features.
=> Refactor the WineShortcut Class

Engines/Wine/Verbs/adobeair/script.js
Fixes: https://github.com/PhoenicisOrg/scripts/issues/1012
Reference: https://github.com/Winetricks/winetricks/pull/1252
=> Update adobeair (fix checksum)

Engines/Wine/QuickScript/GoG Script/script.js
This PR refactors the `GOGScript` class
=> Refactor the GOGScript Class

Engines/Wine/Engine/Implementation/script.js
This PR refactors the Wine engine implementation with some more modern Javascript operations
=> Refactor the Wine Engine Implementation Sourcecode

Engines/Wine/Verbs/xact/script.js
This PR modernizes the Xact verb
=> Refactor the Xact Verb

Engines/Wine/Verbs/d3dx11/script.js
This PR refactors the `d3dx11` verb script and fixes #1089
=> Refactor the "d3dx11" Verb Script

Engines/Wine/Verbs/d3dx10/script.js
This PR modernizes the `d3dx10` verb script
=> Refactor the "d3dx10" Verb Script

Engines/Wine/Engine/Implementation/script.js
Did not test it but it should be fine I guess.
=> Fix trust level not being applied

Engines/Wine/Verbs/Windows XP SP 3/script.js
This PR modernizes the Windows XP SP 3 verb
=> Refactor Windows XP SP 3 Verb Script

Engines/Wine/Verbs/adobeair/script.js
=> Update AdobeAIR verb: remove checksum

Engines/Wine/QuickScript/Steam Script/script.js, Engines/Wine/Verbs/D9VK/script.js, Engines/Wine/Verbs/gdiplus/script.js, Engines/Wine/Verbs/gdiplus_winxp/script.js, Engines/Wine/Verbs/xact/script.js
This PR refactors the steam quick script and applies eslint. In addition it fixes #1106.
=> Refactor the Steam Quick Script

Engines/Wine/Verbs/gdiplus/script.js, Engines/Wine/Verbs/msxml6/script.js
Fix an error in gdiplus and msxml6 script.
=> Update gdiplus and msxml6 verb

Engines/Wine/Verbs/Tahoma/script.js
=> Fix Tahoma Wine Verb

Engines/Wine/Verbs/vcrun6sp6/script.js
=> Fix vcrun6sp6 Wine Verb

Engines/Wine/Verbs/QuickTime 7.6/script.js
fix #1161 
Everything
Nothing
- Operating system (and linux kernel version): Ubuntu 19.10 5.3.0-24-generic
- Hardware (GPU/CPU): GTX 1080 ti, i7-7700K
=> Update QuickTime 7.6 Wine Verb

.github/workflow/lint.yml
see https://github.com/marketplace/actions/run-eslint
I hope that this will make it easier for unexperienced users to understand why Codacy fails and adhere to our coding rules.
=> Use "Run ESLint" GitHub action

Applications/Games/Rocksmith 2014/Steam/script.js, Applications/Games/Rocksmith/Steam/script.js
fixes #1178
untested (I cannot test this currently)
=> Update Rocksmith and Rocksmith 2014 (use virtual desktop instead of awt)

Applications/Games/Space Colony/Local/script.js
fix #1176 
Game Installation, downloading and installing the patch
Nothing
- Operating system (and linux kernel version): ubuntu 19.10
- Hardware (GPU/CPU): gtx 1080ti, i7-7700K
=> Update Space Colony, using arrow pointer, adding parameters to run

Engines/Wine/Verbs/vcrun6sp6/script.js
Fix #1162 
Everything
Nothing
- Operating system (and linux kernel version): ubuntu 19.10
- Hardware (GPU/CPU): gtx 1080 ti, i7-7700K
=> Update vcrun6sp6 Wine Verb (fix cab extract)

Engines/Wine/QuickScript/GoG Script/script.js
=> Install luna in GOGScript

Applications/Games/Epic Games Launcher/Local/script.js, Applications/Games/Epic Games Launcher/Online/script.js
fixes #1200
* fix download URL
* use stable Wine
* install corefonts (not sure if actually required but listed on Wine AppDB)
* do not run OpenGL version (doesn't seem to be required anymore)
* Online installer
* Local installer
=> Fix Epic Games Launcher

Engines/Wine/Engine/Implementation/script.js, Engines/Wine/QuickScript/Installer Script/script.js
32on64 installation choice on macOS
=> 32on64 integration on macOS

.eslintrc.yml
workaround for codacy/codacy-meta#415
=> ESLint: ignore json files

Applications/Games/Mass Effect/Steam/script.js
fixes #1173 
Everything
Nothing
- Operating system (and linux kernel version): Ubuntu 20.04 x64 5.4.0-33-generic
- Hardware (GPU/CPU): i7-7700K, GTX 1080 ti
=> Update Mass Effect, fixed method usage

.travis.yml, package-lock.json, package.json
- run 'npm audit fix'
- change `package.json` (json-align) to ignore `package.json` and `package-lock.json`
- update `.travis.yml` to use `npm run json-align`
=> Run 'npm audit fix'

.github/workflows/update-translations.yml, i18n/Messages.properties, i18n/update_translations.py, validate.py
original problem:
```
E: Unable to locate package python-jsonschema
```
fixed by updating scripts to python 3
=> Fix "update translations" GitHub action

.github/workflows/dependabot.yml, .github/workflows/jsdoc.yml, .github/workflows/linter.yml, .github/workflows/pr-review.yml, .github/workflows/update-translations.yml
otherwise they do not run for PRs from forks
=> Run GitHub actions for PRs

.github/workflows/linter.yml
=> Run linter action on master

Engines/Wine/Verbs/xact/script.js
Update directx_Jun2010_redist.exe checksum in xact verb.
fixes https://github.com/PhoenicisOrg/phoenicis/issues/2424
installing xact. Fixes GOG Galaxy install.
software version : Flatpak 5.0-alpha-3
used operating system : Debian Bullseye (kernel 5.10 x86_64)
used Java version : openjdk version "11.0.11"
- Hardware (GPU/CPU): AMD Juniper (HD5770) / i5-661
=> Update directx_Jun2010_redist.exe checksum in xact

Applications/Games/Hourglass/Local (Demo)/script.js
=> Update Hourglass Demo: fix exe name

Applications/Games/Dreamscapes 2/Online/script.js, Applications/Games/Dreamscapes/Online/script.js
=> Update Dreamscapes (2): fix checksum

docs/_docs/Develop/script-js.md
=> Enhance ZipScript documentation

Applications/Games/Dreamscapes/Online/script.js
=> Update Dreamscapes: fix checksum

Applications/Games/Dreamscapes 2/Online/script.js
=> Update Dreamscapes 2: fix checksum

Applications/Accessories/ImgBurn/Online/script.js, Applications/Development/Notepad++/Online/script.js
=> Update Notepad++ to 8.5 and ImgBurn checksum
