Functions/Engines/Wine/script.js
fixes: Wine.getProgramFiles() returns string with line break at the end #4
=> fixed: Wine.getProgramFiles()

Functions/QuickScript/SteamScript/script.js
The progressbar will not stay at 0bytes but finish as soon as Steam has allocated the required disk space...
=> fix: Steam progressbar stays at 0bytes

Functions/Engines/Wine/script.js
Now, debug must be reset explicitly by calling `wine.debug("")`.
Fixes: fix: wine.debug() always returns empty string #82
=> fixed wine.debug() get

Functions/Engines/Wine/script.js, Functions/Verbs/crypt32/script.js, Functions/Verbs/dotnet40/script.js, Functions/Verbs/mfc42/script.js, Functions/Verbs/vcrun2003/script.js, Functions/Verbs/vcrun2005/script.js, Functions/Verbs/vcrun2008/script.js, Functions/Verbs/vcrun2010/script.js, Functions/Verbs/vcrun2012/script.js, Functions/Verbs/vcrun2013/script.js, Functions/Verbs/vcrun2015/script.js, Games/Age of Empires III: Complete Collection/Steam/script.js
As pointed out by @feanor12 in #168, DLL overrides may not have the suffix .dll. This PR removes .dll from the existing DLL overrides and makes the DLL override function more robust by removing .dll from the input parameters.
fixes #153
=> removed .dll from DLL overrides

Games/League of Legends/BETA Client/script.js
These changes remove the second shortcut and replace it by a bat file.
They also force the BETA client by setting the opt-in flags in user.cfg.
=> Add launch script  to League of Legends and force BETA

Games/Uplay/Online/script.js
I also had to run
```
sudo cp /usr/lib/i386-linux-gnu/libgnutls.so.30 /usr/lib/i386-linux-gnu/libgnutls.so.26
```
to fix
```
err:winediag:schan_imp_init Failed to load libgnutls, secure connections will not be available.
```
Not sure if we can do anything in Phoenicis to fix that error automatically. @qparis any idea?
See also [Wine bug 38466](https://bugs.winehq.org/show_bug.cgi?id=38466)
=> fixed Uplay

Functions/Verbs/uplay/script.js
Some games require Steam and Uplay and do not provide Uplay automatically. I believe that installing Uplay as a verb is the cleanest solution for this (e.g. compared to a new SteamUplayScript).
=> added verb for Uplay

Games/Age of Empires II HD/Steam/script.js
=> Age of Empires II HD: skip broken launcher

Games/Warcraft III TFT/Online/script.js
Check and warn if Warcraft III base game is not installed while installing Warcraft III TFT.
=> Warcraft 3 TFT preinstall check

Functions/QuickScript/InstallerScript/script.js, i18n/Messages_de.properties, i18n/de.po, i18n/keys.pot
requires PlayOnLinux/POL-POM-5#881
Steps:
* Generate the `.pot`:
```bash
find . -iname "*.js" | xargs -d '\n' xgettext --from-code=UTF-8 --language=Javascript -ktr -o i18n/keys.pot
```
* Create a `.po`:
```bash
msginit -i i18n/keys.pot -o i18n/de.po
```
* Translate
* Generate `.properties`
```bash
msgcat --properties-output i18n/de.po -o i18n/Messages_de.properties
```
=> translation via "tr" example

Functions/QuickScript/SteamScript/script.js
The shortcut can only be created that early if the application is started via Steam.exe. However, if the executable is specified directly, this does not yet exist at this point in time.
required by #270
=> SteamScript: create shortcut after installation

Applications/Games/The Vanishing of Ethan Carter Redux/Steam/script.js
Steam doesn't work with the previous version anymore. Moreover, the new version improves the DirectX 11 support.
=> updated The Vanishing of Ethan Carter Redux (new Wine version)

Applications/Games/The Turing Test/Steam/script.js
Steam doesn't work with the previous version anymore. Moreover, the new version improves the DirectX 11 support.
=> updated The Turing Test (new Wine version)

Applications/Games/Rayman Legends/Steam (Demo)/script.js, Applications/Games/Rayman Legends/Steam/script.js
Steam and Uplay do not work with the previous version anymore
=> updated Rayman Legends (new Wine version)

Engines/Wine/QuickScript/SteamScript/script.js
The path of the manifest file will not change during the installation of a Steam application. Therefore it is sufficient to calculate it once.
fixes #331
=> updated SteamScript to cache path of manifest file

Engines/Wine/Engine/Object/script.js, Utils/Functions/Filesystem/Files/script.js, Utils/Functions/Net/Download/script.js
requires PhoenicisOrg/POL-POM-5#979
If the download location is specified (`to()`), the new (`ifUpdateAvailable()`) method can be used to trigger a download only if the resource available via the given URL is newer than the local file.
It is currently used to avoid repeated downloads of the available Wine versions json.
=> updated Downloader with ifUpdateAvailable

Engines/Wine/Engine/Object/script.js, Engines/Wine/Shortcuts/Reader/script.js, Engines/Wine/Shortcuts/Wine/script.js
fixes PhoenicisOrg/POL-POM-5#1013
=> fixed Wine prefix path

Engines/Wine/Engine/Object/script.js
Especially when running several applications at the same time with debug flags set, it is very confusing to have the Wine log in the same output as the Phoenicis log.
fixes #335
=> write Wine log to separate log file

Applications/Internet/Internet Explorer 6.0/Online/script.js, Applications/Internet/Internet Explorer 7.0/Online/script.js, Engines/Wine/QuickScript/InstallerScript/script.js, Engines/Wine/QuickScript/SteamScript/script.js, Engines/Wine/QuickScript/UplayScript/script.js, Engines/Wine/QuickScript/ZipScript/script.js
requires PhoenicisOrg/POL-POM-5#1061
=> show miniature when installing an application

Applications/Internet/Internet Explorer 6.0/Online/script.js, Applications/Internet/Internet Explorer 7.0/Online/script.js, Engines/Wine/Engine/Object/script.js, Engines/Wine/QuickScript/InstallerScript/script.js, Engines/Wine/QuickScript/SteamScript/script.js, Engines/Wine/QuickScript/UplayScript/script.js, Engines/Wine/QuickScript/ZipScript/script.js
requires PhoenicisOrg/POL-POM-5#1064
=> unified setup wizards

Engines/Wine/Verbs/corefonts/script.js
use url from https://raw.githubusercontent.com/Winetricks/winetricks/master/src/winetricks, because previous url does not exist anymore
=> Updated corefonts

.codacy.yml
As the application scripts all look pretty similar, we get many duplication warnings. The warnings for the Wine scripts etc. are still active as they might provide valid information.
=> Codacy: turn off duplication warnings for app scripts

validate.py
The script checks:
* application contains at least one script
* category.json
* application.json
* script.json
* miniatures/main.png (must exist and be 400x300px)
=> added script to validate applications

.travis.yml, i18n/push_translations.sh, i18n/update_translations.py
=> Travis CI: push translation updates (if any)

i18n/push_translations.sh
=> translation updates: handle detached head

i18n/update_translations.py
This should give us an idea about what's going on in Travis.
=> added output to update_translations.py

.travis.yml
If a branch from this repository (not a fork) shall be merged, Travis would execute the checks twice (see e.g. the PRs from crowdin).
=> Travis: avoid double builds on pull requests

Engines/Wine/Shortcuts/Reader/script.js, Engines/Wine/Shortcuts/Wine/script.js, Utils/Functions/Apps/Resources/script.js, Utils/Functions/Filesystem/Extract/script.js, Utils/Functions/Filesystem/Files/script.js, Utils/Functions/Net/Download/script.js, Utils/Functions/Net/Resource/script.js
fixes ESLint "no-unused-vars" warning for globals
see https://eslint.org/docs/rules/no-unused-vars#exported
=> Mark globals as "exported"

Engines/Wine/Shortcuts/Reader/script.js, Engines/Wine/Shortcuts/Wine/script.js, Utils/Functions/Apps/Resources/script.js, Utils/Functions/Filesystem/Extract/script.js, Utils/Functions/Filesystem/Files/script.js, Utils/Functions/Net/Download/script.js, Utils/Functions/Net/Resource/script.js
=> Make Checksum etc. a class

i18n/Messages.properties, i18n/update_translations.py
For whatever reason, xgettext comments all strings in the .properties. I couldn't figure out why this happens so this PR just uses a regex to remove them again after the .properties has been created.
This will probably solve the issue that Crowdin doesn't find any strings in the translation files.
=> Remove comments in Messages.properties

Applications/Games/Prehistorik/Online/script.js, Applications/Games/Prince Of Persia: Original/Online/script.js, Applications/Games/Xenon 2/Online/script.js, Engines/Wine/Verbs/luna/script.js
fixes #592 
I have already merged the counterpart for the 5.0-alpha branch (see #594) to continue testing.
=> Fix repository.playonlinux.com URLs (now https)

i18n/Messages.properties, i18n/update_translations.py
Crowdin interprets it as context of first string
=> Remove header in Messages.properties

.eslintrc.yml, Engines/Wine/Engine/Implementation/script.js
requires #624 and #621
fixes #623
=> Handle Wine archives with directory

Engines/Wine/QuickScript/Steam Script/script.js
Valve changed their SteamInstaller.exe file so the checksum is no longer correct and every steam game instalation crashes.
=> Update SteamScript with new sha1sum

Engines/Wine/Engine/Implementation/script.js, Engines/Wine/Engine/Object/script.js, Engines/Wine/QuickScript/Steam Script/script.js
If multiple programs are running in a prefix, `wineserver -w` will wait until all of them are finished. Therefore, the `wait` parameter in `Wine#run()` waits only until the started process is finished. `Wine#wait` can be used to explicitly wait until the wineserver is closed.
fixes #671
=> Wine#run(): do not wait for wineserver

Applications/Games/Steam/Online/script.js, Engines/Wine/QuickScript/Steam Script/script.js
Two changes were made:
1. Update the out-of-date SHA1 checksum of SteamSetup.exe.
2. Change HTTP links to HTTPS.
=> Update Steam URL and Checksum

Engines/Wine/Verbs/mspatcha/script.js
This pull request resolves issue #706. The URL for mspatcha is changed from 
```
http://ftp.anadolu.edu.tr/Service_Packs/Windows_2000/W2ksp4_EN.exe"
```
to
```
https://ftp.gnome.org/mirror/archive/ftp.sunet.se/pub/security/vendor/microsoft/win2000/Service_Packs/usa/W2KSP4_EN.EXE
```
Note that this file has the same SHA1 checksum as the original link at (http://ftp.anadolu.edu.tr/Service_Packs/Windows_2000/W2ksp4_EN.exe):
```
fadea6d94a014b039839fecc6e6a11c20afa4fa8
```
=> Fix mspatcha URL

Applications/Games/Epic Games Launcher/Online/script.js
Doesn't run due to Wine bug [41258](https://bugs.winehq.org/show_bug.cgi?id=41258) but at least it installs again.
=> Update Epic Games Launcher (fix checksum)

docs/_docs/General/best-practices.md
See https://github.com/PhoenicisOrg/phoenicis/issues/1711
=> Improve the best practices for the creation of custom scripts

Engines/Wine/Verbs/FAudio/script.js
Only call `this.system64directory()` for 64 bits container.
=> Update Faudio verb

docs/_docs/Develop/verbs.md
=> Add precision about windows dll's destination

Applications/Games/Star Craft II/Online/script.js
So here's the story:
An user form POL4 website was reporting the POL4 version of this script wasn't working due to broken link in flashplayer. I've told him to switch to POL5 since it have a more active support. Right after that I've checked if the script is still working. Right after the login screen appeared I get the "Starcraft2.exe not found" error. The script dosen't wait long enough so I did what @Kreyren did and changed it to Battle.net.exe
And while I was at it I've changed `wineVersion` to use the latest stable Wine.
=> Update Starcraft II (use latest stable Wine, fix executable name)

Applications/Games/Overwatch/Online/script.js, Applications/Games/Overwatch/Online/script.json
DISCLAIMER: 'needs approval' meaning that i'm not sure by syntax.
SOLVED: WindowsXP is unsupported by upstream to install OW. -> Windows 7+ is mandatory
SOLVED: `DXVK` is mandatory for performance, 
SOLVED: `WINEDEBUG="-all"` is mandatory for performance
-- Should be present by default if game is launched from phoenicis.
HOTFIXED: Phoenicis installer crashes once the game is installed and openned in Battle.net launcher -> Game is then not recognized by phoenicis
-- Relevant https://github.com/PhoenicisOrg/scripts/issues/792
-- Needs fix
TODO: Add preloaded cache which helps with loading and frezes when player enters and/or interacts with items. Requires playing the game and then exporting cache.
TODO: Esync needs revision with changes above.
*low priority, needs testing*
`ESYNC` is …
=> Update Game/Overwatch : fixes

Applications/Games/Space Colony/Local/script.js
Since wine 4.2 the issue described in `preInstall` no longer exist, we are removing the message. Ready for review.
=> Update Space Colony, removed pre install message

Engines/Wine/QuickScript/Local Installer Script/script.js, Engines/Wine/QuickScript/Online Installer Script/script.js
Ensure that args are always an array internally even if only a string is passed to `installationArgs()`. Moreover, avoid that args are `[[]]` if no args have been set.
=> Update Local/Online Installer Script to handle args correctly

Engines/Wine/QuickScript/Origin Script/script.js
Every time Origin gets updated checksum changes which results in a error when installing an Origin game.
=> Update OriginScript, removing checksum

Engines/Wine/QuickScript/Steam Script/script.js
- run {steamwebhelper.exe,steam.exe} with winxp to fix steam browser
- run {UbisoftGameLauncher.exe,upc.exe} with winvista to fix rendering issues in uplay client
\+ corefonts because they are used by steam
=> Update SteamScript (fix Steam browser and Uplay rendering issues)

Applications/Games/Assassin's Creed III/Steam/script.json, Engines/Wine/Verbs/FAudio/script.js
As refferenced on https://github.com/PhoenicisOrg/scripts/pull/967#issuecomment-499492492 this script is not working -> push in testing
=> Mark Assassin's Creed III as "testing" (Uplay not working)

Engines/Wine/Engine/Implementation/script.js
Btw @qparis the json from https://phoenicis.playonlinux.com/index.php/runtime?os=linux has not been updated.
=> Fix runtime not being correctly added to the ldpath

Engines/Wine/QuickScript/Custom Installer Script/script.js, Engines/Wine/QuickScript/GoG Script/script.js, Engines/Wine/QuickScript/Installer Script/script.js, Engines/Wine/QuickScript/Local Installer Script/script.js, Engines/Wine/QuickScript/Online Installer Script/script.js, Engines/Wine/QuickScript/Origin Script/script.js, Engines/Wine/QuickScript/Quick Script/script.js, Engines/Wine/QuickScript/Steam Script/script.js, Engines/Wine/QuickScript/Uplay Script/script.js, Engines/Wine/QuickScript/Zip Script/script.js
This PR refactors the quick script classes with the newer and better understandable JavaScript class syntax. In addition this PR replaces the `var` keyword with the `const` or `let` keyword depending on whether the variable is a constant or not.
@plata @qparis @ImperatorS79 I've tested the changes in this PR by reinstalling Notepad++. Because this only uses three of the quick script classes it would be nice if you can test some of the others, which I'm unable to (origin, gog, local, custom, uplay, zip)
=> Refactor the Quick Script Classes

Engines/Wine/Tools/Wine Terminal Opener/script.js
I will add libncurses 32 bits in the runtime also since I found why it did not work, but it needs this.
=> Fix an error with libncurses from runtime

Applications/Multimedia/Mp3tag/Online/script.js
Before the change the script wold give the "cheksum mismatch" error.
Everything
Nothing
- Operating system (and linux kernel version): Ubuntu 19.04 x64 (5.0.0-17-generic)
CPU: i7-7700L
GPU: Zotac GTX 1080 TI mini
=> Update Mp3tag, updated link and checksum

Engines/Wine/Verbs/DXVK/script.js
The only issue I noticed is I get the error message that is supposed to be displayed when run on Macs.
Aside from above mentioned, everything.
Nothing
- Operating system (and linux kernel version): Ubuntu 19.04 x64 (5.0.0-16-generic)
CPU: i7-7700K
GPU:Zotac GTX 1080 Ti mini
=> Update DXVK (add version 1.2.2)

Engines/Wine/Verbs/FAudio/script.js
Added version 19.06 and 19.06.07. When installing 19.06.07 this error shows up when the script is trying to extract the .sh file:
```
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/Space Engineers/FAudio/faudio-19.06.07/wine_setup_faudio.sh (493).
[ERROR] org.phoenicis.multithreading.ControlledThreadPoolExecutorService (l.64) - org.graalvm.polyglot.PolyglotException
at java.base/java.util.Arrays.stream(Arrays.java:5614)
at org.phoenicis.tools.files.FileUtilities.ls(FileUtilities.java:49)
at <js> ls(utils.functions.filesystem.files:12:393-438)
at <js> Wine.faudio(engines.wine.verbs.faudio:34:1140-1161)
at <js> install(engines.wine.verbs.faudio:68:2213-2245)
at org.graalvm.sdk/org.graalvm.polyglot.Value.executeVoid(Value.j …
```
=> Update FAudio (add new versions, remove x32 support)

Engines/Wine/Engine/Implementation/script.js
Only can be seen for a first installation. 
@qparis There is nor runtime x86 with name 201906221529, which will cause bugs since the runtime code expect amd64 and x86 runtime to have the same name (and it should be the same since they are always updated at the same time). I recommand you delete the runtime.json and all the stored runtime archives and properly upload latest amd64 and x86 runtime and a new runtime.json.
=> Update runtime: fix an error when a directory does not exist

Engines/Wine/QuickScript/Quick Script/script.js, Utils/Functions/Filesystem/Extract/script.js
This PR refactors both the `CabExtract` and `Extract` classes with the new ES 6 `class` syntax.
In additional some small code improvements have been made
=> Refactor both the CabExtract and the Extract Classes

Engines/Wine/QuickScript/Quick Script/script.js, Utils/Functions/Apps/Resources/script.js
This PR refactors the `AppResource` class. This contains:
- change the class to use the newer ES 6 `class` syntax
- fetch the `ApplicationDTO` object already in the `application(application)` method
- forbid `null` return values, throw errors instead. Normally a script **expects** a fetched file to exist
=> Refactor the "AppResource" class

Engines/Wine/Engine/Implementation/script.js
The bug came from the fact that x86 and amd64 runtime does not necessary have the same name
@Kreyren once this is loaded, could delete runtime and runtime.json in .Phoenicis/engines/wine, then retest steam game installation
=> Fix x86 runtime not being downloaded

Engines/Wine/Verbs/gallium9/script.js
=> Fix bad class naming for gallium 9 verb

Engines/Wine/QuickScript/Installer Script/script.js
This PR does some additional code cleanup in the `InstallerScript` class
=> Refactor InstallerScript

Applications/Games/Space Engineers/Steam/script.js, i18n/Messages.properties
fixed typo on string 386: `peroid` > `period`
it work
There is no test applied
MacOSX Mojave
Macbook
=> Update Space Engineers (fix typo in message)

Engines/Wine/Engine/Object/script.js
This PR refactors the Wine engine object with newer JS language features like `class` and streams
=> Refactor the Wine Engine Object

Engines/Wine/Verbs/vcrun2003/script.js
This PR refactors the `vcrun2003` verb script and fixes #1086
=> Refactor the "vcrun2003" Verb Script

Engines/Wine/Verbs/d3dx9/script.js
This PR modernizes the `d3dx9` verb script
=> Refactor the "d3dx9" Verb Script

Engines/Wine/Verbs/corefonts/script.js
This PR refactors the `corefonts` verb script and fixes #1092
=> Refactor the "corefonts" Verb Script

Utils/Functions/Apps/PlainInstaller/script.js, Utils/Functions/Apps/Resources/script.js, Utils/Functions/Filesystem/Extract/script.js, Utils/Functions/Filesystem/Files/script.js, Utils/Functions/Net/Download/script.js, Utils/Functions/Net/Resource/script.js, Utils/Functions/System/virtual desktop/script.js
This PR improves the code quality of the `Utils` scripts by:
- extracting the `Bean(...)` and `Java.type(...)` calls to the front of the utils scripts
- removing the now unnecessary `// eslint-disable-next-line no-unused-vars` comments
In addition this PR fixes some small issues
=> Improve Code Quality of the Utils Scripts

Engines/Wine/Engine/Implementation/script.js, Engines/Wine/Engine/Object/script.js
This PR extracts the usage of `Bean(...)` and `Java.type(...)` to the front of the wine engine scripts.
=> Extract "Bean(...)" and "Java.type(...)" Usage in Wine-Engine

Applications/Games/Space Engineers/Steam/script.js
It should be `no-cef-sandbox` not `no-ces-sandbox`
Everything but sometimes Wine decides to force ALSA instead of PulseAudio. This results in even choppier audio. But when I use winetricks to set it to pulse and go to the sound tab in winecfg I get "none" next to the "chosen driver".
Nothing I can think of at this moment
- Operating system (and linux kernel version): Ubuntu 19.04 x64 5.0.0-25-generic
i7-7700K, GTX 1080 ti
=> Update Space Engineers, bumped up wine version and fixed few typos

docs/_docs/General/best-practices.md, docs/_docs/General/classes.md, docs/_docs/General/module-system.md, docs/_docs/General/tools.md, docs/_docs/General/translation.md
This PR adds a short article about the usage of the module system
=> Add Documentation about the Module System

Engines/Wine/Verbs/FAudio/script.js
Seemingly everything (when `Space Engineers` use this version of the verb the audio tab in winecfg is corectly set to winepulse instead of ALSA which produces better audio) but I got this error when installing faudio 19.08 on a existing `Space Engineers` prefix:
```
[ERROR] net.sf.jmimemagic.MagicMatcher (l.731) - failed to load detector: 
net.sf.jmimemagic.detectors.TextFileDetector
java.lang.ClassNotFoundException: 
net.sf.jmimemagic.detectors.TextFileDetector
at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
at java.base/java.lang.Class.forName0(Native Method)
at …
```
=> Update FAudio, added new versions

Engines/Wine/Engine/Implementation/script.js
It is sufficient to download/update the runtime once during one installation. We can safely assume that the runtime does not change during this period of time.
fixes #1055
=> Avoid that runtime is installed multiple times during one installation

Engines/Wine/Engine/Implementation/script.js
set `application.environment.wineRuntime`, by default the runtime is used
fixes https://github.com/PhoenicisOrg/phoenicis/issues/1940
=> Add property to (not) use Wine runtime

Applications/Games/Steam/Online/script.js, Engines/Wine/QuickScript/Steam Script/script.js
After Steam overhauled their Library tab, support for windows xp was dropped entirely. This results in Steam client unable to start which breaks the sequence of events neceseary to get this script to work. Still need to figure out a new way to make both steam browser and library tab work. Currently both elements either dosen't work at all (black page) or work partially (page goes to black when scrolling, page displayed with black rectangles on some content, makes the `<div>` elements visible). A partial fix to #1138 
Installing games.
Nothing
- Operating system (and linux kernel version): Ubuntu 19.10 5.3.0-19-generic
- Hardware (GPU/CPU): i7-7700K, GTX 1080 ti
=> Update SteamScript (remove winxp overrides)

Engines/Wine/Plugins/override DLL/script.js
=> Fix Wine plugin "Override DLL"

Applications/Internet/Internet Explorer 6.0/Online/script.js, Applications/Internet/Internet Explorer 7.0/Online/script.js, docs/_docs/Develop/script-js.md
I forgot it in https://github.com/PhoenicisOrg/scripts/pull/1153/commits/320fd390821116d3e145945958201a013e836058.
=> Add missing architecture parameter to getLatestStableVersion() calls

Engines/Wine/Verbs/D9VK/script.js, Engines/Wine/Verbs/FAudio/script.js, Engines/Wine/Verbs/VK9/script.js, Engines/Wine/Verbs/gallium9/script.js, Utils/Functions/Net/GithubReleases/script.js
=> Return Github "version" Objects instead of the tag Strings

Engines/Wine/QuickScript/Installer Script/script.js
Thanks to #1144 we have discovered that scripts will fail if `.executable()` points to a file that only exist after `postInstall` step is done. Since @plata mentioned something about Installer Script working this way for a reason (though I was unable to find that reason in closed PRs and issues) this is a WIP draft untill me or someone else test this with other scripts that use `postInstall`.
`Heroes of Might & Magic IV` no longer crash due to non-existing `.executable()`
Other scripts with `postInstall`
- Operating system (and linux kernel version): Ubuntu 19.10
- Hardware (GPU/CPU): GTX 1080 ti, i7-7700K
=> Update Installer Script (run postInstall before shortcut creation)

Engines/Wine/Engine/Implementation/script.js
fix https://github.com/PhoenicisOrg/phoenicis/issues/2172
Shortcuts and running exe files 
How the script will behave if file in `runtimeJsonPath` is empty.
- Operating system (and linux kernel version): Ubuntu 19.04 x64 5.3.0-29-generic
- Hardware (GPU/CPU): GTX 1080 ti, i7-7700K
=> Update Implementation, changed how old runtimes are defined and improved the check for runtime.json

.github/workflows/lint.yml, .gitignore, Engines/Wine/Engine/Implementation/script.js, docs/_docs/General/tools.md, package-lock.json, package.json
Codacy does not work reliably lately and the configuration is more difficult compared to GitHub actions.
`package.json` is required (otherwise the action does not run)
eslint and json-align can now be started via npm (thanks to @madoar)
=> ESLint action (reviewdog)

Applications/Games/Steam/Online/script.js, Engines/Wine/QuickScript/Steam Script/script.js
Steam installer now outputs `steam.exe` instead of `Steam.exe` which leads to errors
Installing Steam game
Nothing
- Operating system (and linux kernel version): Ubuntu 20.04 x64 5.4.0-37-generic 
- Hardware (GPU/CPU): i7-7700K, GTX 1080 ti
=> Update SteamScript, changed .exe filename to lowercase

Engines/Wine/Verbs/mspatcha/script.js
Simply replace a dead download link with a working one from archive.org
The Adobe Acrobat Reader DC installer is now working instead of hanging at the download step.
Everything else
- Operating system (and linux kernel version): Fedora 32
- Hardware (GPU/CPU): -
=> Update W2KSP4_EN.EXE URL to web.archive.org

Applications/Games/Subnautica/Steam/script.js
The content of that link was moved to a different one.
=> Update Subnautica, using the updated link for Esync guide

Engines/Wine/Verbs/corefonts/script.js
The URLs in the Wine corefonts verb didn't work anymore.
Use URLs from winetricks.
Fixes https://github.com/PhoenicisOrg/phoenicis/issues/2785.
=> corefonts: fix download URLs
